services:
  postgres:
    image: postgres:17-alpine
    container_name: lap_db
    restart: always
    env_file:
      - .env
    ports:
      - ${PORTS}
    volumes:
      - postgres_data_lap:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dbnet
    deploy:
      resources:
        limits:
          cpus: ${CPUS_LIMIT}
          memory: ${MEMORY_LIMIT}
        reservations:
          cpus: ${CPUS_RESERVE}
          memory: ${MEMORY_RESERVE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: ${INTERVAL}
      timeout: ${TIMEOUT}
      retries: ${RETRIES}
      start_period: ${START_PERIOD}

  redis:
    image: redis:8-alpine
    container_name: lap_redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data_lap:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - dbnet
    deploy:
      resources:
        limits:
          cpus: ${REDIS_CPUS_LIMIT}
          memory: ${REDIS_MEMORY_LIMIT}
        reservations:
          cpus: ${REDIS_CPUS_RESERVE}
          memory: ${REDIS_MEMORY_RESERVE}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: ${REDIS_INTERVAL}
      timeout: ${REDIS_TIMEOUT}
      retries: ${REDIS_RETRIES}
      start_period: ${REDIS_START_PERIOD}

networks:
  dbnet:
    driver: bridge

volumes:
  postgres_data_lap:
  redis_data_lap:


